ElectricComponentCalculator/Controllers/ResistorConfigurationController.cs
using DocumentStorage;
using Raven.Client;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ElectricComponentCalculator.Controllers
{
    public class ResistorConfigurationController : Controller
    {
        private readonly IDocumentStore db;

        public ResistorConfigurationController(IDocumentStore db)
        {
            this.db = db;
        }

        // GET: ResistorConfiguration
        public ActionResult Index()
        {
            IList<ResistorColorCode> model = new List<ResistorColorCode>();

            using (var session = db.OpenSession())
            {
                model = (from r in session.Query<ResistorColorCode>()
                               select r).ToList();
            }
            
            return View(model);
        }

        [HttpPost]
        public ActionResult GetItem(string color)
        {
            ResistorColorCode code = null;

            using (var session = db.OpenSession())
            {
                code = session.Query<ResistorColorCode>().FirstOrDefault(r => r.Color == color);

                if ( code == null )
                {
                    return new HttpNotFoundResult();
                }
            }

            return PartialView("_ItemResistorCode", code);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("CreateResistorColor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( ResistorColorCode colorCode )
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            // verify does not already exist
            using (var session = db.OpenSession())
            {
                var exists = session.Query<ResistorColorCode>().Any(r => r.Color == colorCode.Color);

                if ( exists )
                {
                    ModelState.SetModelValue("Color", new ValueProviderResult("Color already exists", colorCode.Color, CultureInfo.InvariantCulture));
                    return View();
                }

                session.Store(colorCode);
                session.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateResistorColor( string Color)
        {
            ResistorColorCode code = null;

            using (var session = db.OpenSession())
            {
                code = session.Query<ResistorColorCode>().FirstOrDefault(r => r.Color == Color);
                if ( code == null )
                {
                    return new HttpNotFoundResult();
                }
            }

            return PartialView("_EditResistorCode", code);
        }

        [HttpPost]
        public ActionResult Save( ResistorColorCode model )
        {
            if (!ModelState.IsValid )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var session = db.OpenSession())
            {
                session.Store(model);
                session.SaveChanges();
            }

            return PartialView("_ItemResistorCode", model);
        }


        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Delete)]
        public ActionResult DeleteResistorColor(string color)
        {
            using (var session = db.OpenSession())
            {
                var code = session.Query<ResistorColorCode>().FirstOrDefault(r => r.Color == color);

                if ( code == null )
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Color does not exist!");
                }

                session.Delete(code);
                session.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        //[HttpGet]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteResistorColor(ResistorColorCode item)
        //{
        //    using (var session = db.OpenSession())
        //    {
        //        var code = session.Query<ResistorColorCode>().FirstOrDefault(r => r.Color == item.Color);

        //        if (code == null)
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Color does not exist!");
        //        }

        //        session.Delete(code);
        //        session.SaveChanges();
        //    }

        //    return new HttpStatusCodeResult(HttpStatusCode.OK);
        //}
    }
}

ElectricComponentCalculator/Views/ResistorConfiguration/CreateResistorColor.cshtml
@using DocumentStorage
@model ResistorColorCode

@{
    ViewBag.Title = "Create Resistor Color Code";
}
<h4>@ViewBag.Title</h4>
@using (Html.BeginForm("Create", "ResistorConfiguration", FormMethod.Post, new { role = "form" }))
{
    <div class="form-horizontal">

        @Html.AntiForgeryToken()
        <hr />
        <div class="form-group">
            <label class="control-label" for="color">Color:</label>
            <input id="color" class="form-control" type="text" name="Color" placeholder="Enter Color Name ..." required />
        </div>
        <div class="form-group">
            <label class="control-label" for="SignificantDigit">Significant Digit:</label>
            <input id="SignificantDigit" class="form-control" type="number" name="SignificantDigit" placeholder="Enter Significant Digit ..." min="0" max="9" pattern="\d" title="Significant Digit" />
        </div>
        <div class="form-group">
            <label class="control-label" for="Multiplier">Multiplier:</label>
            <input id="Multiplier" class="form-control" type="number" name="Multiplier" placeholder="Enter Multiplier ..." title="Mulitplier Decimal" />
        </div>
        <div class="form-group">
            <label class="control-label" for="Tolerance">Tolerance:</label>
            <input id="Tolerance" class="form-control" type="number" name="Tolerance" placeholder="Enter Tolerance Value ..." title="Tolarence Digit" />
        </div>
        <div class="form-group">
            <label class="control-label" for="ToleranceCode">Tolerance Code:</label>
            <input id="ToleranceCode" class="form-control" type="text" name="ToleranceCode" placeholder="Enter Tolerance Code ..." pattern="[A-Z]{1}" title="Tolerance Code" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectricComponentCalculator/Views/ResistorConfiguration/Index.cshtml
@using DocumentStorage;

@model List<ResistorColorCode>

@{

    ViewBag.Title = "Resistor Color Code Admin";
}

<h2>@ViewBag.Title</h2>
@Html.AntiForgeryToken()
<div id="ResistorColorAdminContent">
    <p>
        @Ajax.ActionLink("Create New", "Create", "ResistorConfiguration", routeValues: null, htmlAttributes: new { id = "CreateLink" }, ajaxOptions: new AjaxOptions { InsertionMode = InsertionMode.ReplaceWith, UpdateTargetId = "ResistorColorAdminContent" })
    </p>
    <div id="ResistorColorTable" class="container">
        <table class="table table-bordered table-striped wrapped">
            <thead class="thead-default">
                <tr class="row">
                    <td>
                        Color
                    </td>
                    <td>
                        Significant Digit
                    </td>
                    <td>
                        Multipiler
                    </td>
                    <td>
                        Tolerance
                    </td>
                    <td>
                        Tolerance Code
                    </td>
                    <td>
                        Actions
                    </td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    Html.RenderPartial("_ItemResistorCode", item);
                }
            </tbody>


        </table>
    </div>
</div>  

ElectricComponentCalculator/Views/ResistorConfiguration/_EditResistorCode.cshtml
@model DocumentStorage.ResistorColorCode


<tr id="@(Model.Color)_Edit" class="row">
    <td>
        <div class="col-md-10">
            @Model.Color
        </div>
    </td>
    <td>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SignificantDigit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SignificantDigit, "", new { @class = "text-danger" })
        </div>
    </td>
    <td>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Multiplier, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Multiplier, "", new { @class = "text-danger" })
        </div>
    </td>
    <td>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tolerance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tolerance, "", new { @class = "text-danger" })
        </div>
    </td>
    <td>
        <div class="form-group col-md-10">
            <input id="ToleranceCode" class="form-control" name="TolaranceCode" value="@Model.ToleranceCode"  type="text"/>
            @Html.ValidationMessageFor(model => model.ToleranceCode, "", new { @class = "text-danger" })
        </div>

    </td>
    <td>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Save", "ResistorConfiguration")' data-val="true" data-ajax-begin="alert('validating'); debugger; $.validator.unobtrusive.parse('@(Model.Color)_Edit'); $('@(Model.Color)_Edit').validate();" data-ajax-form-id="@(Model.Color)_Edit" data-ajax-update="@(Model.Color)_Edit" data-ajax-mode="replace-with" data-ajax="true" data-ajax-method="Post" data-ajax-failure="Alert('Failed to update!')">Save</a>
                @Ajax.ActionLink("Save", "Save", "ResistorConfiguration", Model,
                   new AjaxOptions() { InsertionMode = InsertionMode.ReplaceWith, UpdateTargetId = Model.Color + "_Edit", HttpMethod = "Post", OnFailure = "Alert('Failed to update!')" })
                @Ajax.ActionLink("Cancel", "GetItem", "ResistorConfiguration", new { Color = Model.Color },
                       new AjaxOptions() { InsertionMode = InsertionMode.ReplaceWith, UpdateTargetId = Model.Color + "_Edit", HttpMethod = "Post", OnFailure = "Alert('Failed to return to list!')" })

            </div>
        </div>
    </td>
</tr>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectricComponentCalculator/Views/ResistorConfiguration/_ItemResistorCode.cshtml
@using DocumentStorage

@model ResistorColorCode

<tr id="@(Model.Color)_Item" class="row">
    <td><div class="col-md-10">@Model.Color</div></td>
    <td><div class="col-md-10">@Model.SignificantDigit</div></td>
    <td><div class="col-md-10">@Model.Multiplier</div></td>
    <td><div class="col-md-10">@Model.Tolerance</div></td>
    <td><div class="col-md-10">@Model.ToleranceCode</div></td>
    <td>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Ajax.ActionLink("Edit", "UpdateResistorColor", new { color = Model.Color }, ajaxOptions: new AjaxOptions() {  UpdateTargetId = Model.Color + "_Item", InsertionMode = InsertionMode.ReplaceWith, HttpMethod = "Post" })
                @Ajax.ActionLink("Delete", "DeleteResistorColor", new { color = Model.Color },
       new AjaxOptions()
       {
           Confirm = "Continue to delete color " + Model.Color + "?",
           OnSuccess = "$('#" + Model.Color + "_Item').remove()",
           OnFailure = "alert('failed')",
           HttpMethod = "Delete"
       })
                @Ajax.ActionLink("DeleteApi", "Delete", "api/ResistorCode", new { color = Model.Color },
       new AjaxOptions()
       {
           Confirm = "Continue to delete color " + Model.Color + "?",
           HttpMethod = "Delete",
           OnSuccess = "$('#" + Model.Color + "_Item').remove()",
           OnFailure = "alert('failed');"
       })
            </div>
        </div>
    </td>
</tr>